name: Post-Merge Validation

on:
  push:
    branches:
      - master

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'

      - name: Upgrade pip and install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build the package
        run: |
          python -m build

      - name: Validate package metadata with Twine
        run: |
          twine check dist/*

      - name: Create virtual environment and install package
        run: |
          python -m venv env
          source env/bin/activate
          pip install --upgrade pip
          pip install dist/*.whl
          # Sanity check: try importing the package
          python -c "import common_python; print('common_python imported successfully')"

